# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'RickMoya' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxFlow'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'R.swift'
  pod 'IQKeyboardManagerSwift'
  pod 'NotificationBannerSwift'
  pod 'Moya/RxSwift', '~> 12.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 5.0'

  # Pods for RickMoya

end
